### ISSUE TITLE
OOSI: Design the Link-in-bio page for click matrics

### ISSUE THREAD

**Issue by krishna-singha** [oxiton-foundation/click-metrics#5]
# Current:

<img width="1710" alt="Screenshot 2024-05-13 at 11 29 56 PM" src="https://github.com/Websimpl-Foundation/click-metrics/assets/128041532/047058c1-77ee-436f-a62a-64ea5a54ebfa">

<br>

# Expected Result:

<img width="1710" alt="Screenshot 2024-05-14 at 12 09 57 AM" src="https://github.com/Websimpl-Foundation/click-metrics/assets/128041532/ff989bf0-7f55-46a8-ae9d-aecbc04a35ad">
<img width="1710" alt="Screenshot 2024-05-14 at 12 10 04 AM" src="https://github.com/Websimpl-Foundation/click-metrics/assets/128041532/c2c1b7e7-5d10-4934-ae75-0730b764f5d6">

**Comment by lazybug19** [comment]
I have followed the page/registered with username Santrupti/lazybug19, according to OOSI guidelines. Kindly assign me this issue, I would like to work on it.

**Comment by krishna-singha** [comment]
@lazybug19 Can you discuss your approach and also mention everything with a proper timeline and tech stack. Go through #24

**Comment by lazybug19** [comment]
@krishna-singha 
Tech stack: Next.js, TailwindCSS, Framer Motion library, if needed, for animations/better UI, MongoDB for data storage and retrieval.
Approach/Features and Timeline:
- [ ] **31st May (Friday)** : Instead of creating multiple templates to choose from which limits the total options, a form like template with radio buttons/toggle to choose background image, profile logo, theme color and link-in-bio page name can be built to customize according to users.
![image](https://github.com/oxiton-foundation/click-metrics/assets/105040967/09169039-87ac-40ed-9daf-e1c34de0fa6c)
- [ ] **2nd June** : Connect uri and maintain concurrency. Store and retrieve user template info using MongoDB and mongoose.

**Comment by dhruv8433** [comment]
@Swarnendu0123 

i would like to work on this issue
i can create it as you say 
please assign it me i will try my best

**Comment by lazybug19** [comment]
@krishna-singha @Swarnendu0123 any update?
